name: Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build -c Release src/OneHub.Tools.HeapView/OneHub.Tools.HeapView.csproj
    - name: Pack      
      run: dotnet pack -c Release src/OneHub.Tools.HeapView/OneHub.Tools.HeapView.csproj
    - name: Publish the package to nuget.org
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: dotnet nuget push nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}      
